### PR TITLE
Add prettier check step

### PR DESCRIPTION
**Pull request by pedro-avalos**
Addresses #16

### CODE REVIEW

**Comment by 3timeslazy** [comment]
Hi @pedro-avalos 

I ran the script locally and got:

```sh
$ pnpm prettier:check
 ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command "prettier:check" not found

Did you mean "pnpm prettier"?
```

The reason it that there is no such script in package.json. Could you please add it there as well? 

A random example from GitHub: https://github.com/FuelLabs/fuel-ui/blob/master/package.json#L41

**Comment by pedro-avalos** [comment]
> Hi @pedro-avalos 
> 
> I ran the script locally and got:
> 
> ```sh
> $ pnpm prettier:check
>  ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command "prettier:check" not found
> 
> Did you mean "pnpm prettier"?
> ```
> 
> The reason it that there is no such script in package.json. Could you please add it there as well? 
> 
> A random example from GitHub: https://github.com/FuelLabs/fuel-ui/blob/master/package.json#L41

Ah you're right, I'll add it. So sorry about that. 😅

**Comment by pedro-avalos** [comment]
@3timeslazy I've added the script now, let me know if you need anything else :smile:

**Comment by 3timeslazy** [comment]
Thank you for the contribution!

If you'd like, I can make an issue with CI/CD improvements. It's already in the code as a TODO, but I could specify the details

**Comment by pedro-avalos** [comment]
> Thank you for the contribution!
> 
> If you'd like, I can make an issue with CI/CD improvements. It's already [in the code as a TODO,](https://github.com/3timeslazy/vscodium-devpodcontainers/blob/main/.github/workflows/build.yml#L3) but I could specify the details

I noticed that, and I was hoping to attend to that next. I think it would be best to have an issue with some details, if possible. Thanks!

**Pull request merged**
